const fs = require('fs');
const path = require('path');

const { withDangerousMod } = require('@expo/config-plugins');

/**
 * Content of `ios/.xcode.env.local`, which tells Xcode's script phases where Node is.
 *
 * Those phases run in a sanitised shell with no nvm on PATH, so without this the
 * Hermes and React Native dependency scripts die with `node: No such file or
 * directory`. It resolves Node through nvm rather than naming a path, because every
 * absolute path here rots: a Homebrew revision bump or an `nvm install` moves the
 * binary and the next build breaks with no code change.
 */
const XCODE_ENV_LOCAL = `# Generated by plugins/withXcodeEnvNvm.js during prebuild — edits here are overwritten.
#
# .nvmrc is the single source of truth for the Node version — local shells, EAS
# Build and this file all read it — so nothing below names a version or a path.
export NVM_DIR="\${NVM_DIR:-$HOME/.nvm}"
. "$NVM_DIR/nvm.sh" --no-use || { echo "error: nvm not found at $NVM_DIR" >&2; exit 1; }

# Resolved relative to this file (ios/.xcode.env.local), because Xcode makes no
# promise about the working directory a script phase runs in.
_ss_node="$(cat "$(dirname "\${BASH_SOURCE[0]:-$0}")/../.nvmrc")"
nvm use --silent "$_ss_node" || { echo "error: Node $_ss_node from .nvmrc is not installed — run: nvm install" >&2; exit 1; }
unset _ss_node

export NODE_BINARY=$(command -v node)
`;

/**
 * Generates `ios/.xcode.env.local` on every prebuild.
 *
 * It has to be generated rather than written once by hand: `ios/` is gitignored and
 * rebuilt by prebuild, so `expo prebuild --clean` would otherwise take the fix away
 * and leave a build that fails for reasons unrelated to the change you just made.
 * Generating it also means a fresh clone works on the first `npm run ios`.
 */
module.exports = function withXcodeEnvNvm(config) {
  return withDangerousMod(config, [
    'ios',
    (cfg) => {
      fs.writeFileSync(
        path.join(cfg.modRequest.platformProjectRoot, '.xcode.env.local'),
        XCODE_ENV_LOCAL,
      );
      return cfg;
    },
  ]);
};
